# Dockerfile for news-feed-service
FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o news-feed-service .

FROM alpine:latest

COPY --from=builder /app/news-feed-service /news-feed-service

RUN chmod +x /news-feed-service

EXPOSE 8082

CMD ["/news-feed-service"]
