---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dothaibao.
--- DateTime: 24/9/24 15:45
---

wrk.headers["Authorization"] = "wrk-stress-test"
wrk.headers["Content-Type"] = "application/json"

-- Function to generate a random user ID
local function getUserId()
    -- Generate a random user ID between 11878102 and 21878101
    return math.random(11878102, 21878101)
end

-- Function to generate a cursor
local function getCursor()
    local cursorChoice = math.random(1, 2) -- Randomly choose a value from 1 to 10
    if cursorChoice == 1 then
        return 0 -- 10% chance to return 0
    else
        -- Generate a random cursor value between 11878102 and 21878101
        return math.random(11878102, 21878101)
    end
end

-- Request function
request = function()
    local userId = getUserId() -- Get a random user ID
    local cursor = getCursor() -- Get a random cursor value
    local limit = 10
    local url = "http://localhost:8080/v1/friends/" .. userId .. "?cursor=" .. cursor .. "&limit=" .. limit

    return wrk.format("GET", url)
end